config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root "users#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get '/home', to: 'static_pages#home'
  get '/app', to: 'apps#index'
  resource :category
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :title, uniqueness: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = current_user.categories
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(categories_params)
    respond_to do |format| 
      if @category.save
        format.turbo_stream
        redirect_to app_path
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def categories_params
    params.require(:category).permit(:title)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/apps/index.html.erb
<div class="app">
  <section class="app-top-nav">
    <nav class="top-nav">
      <div class="nav-left">
        <button class="menu-btn">&#9776;</button>
        home button
      </div>
      <div class="nav-right">
        create task
        profile
      </div>
    </nav>
  </section>
  <section class="app-side-nav">
    <nav class="side-nav">
      <div>Dashboard</div>
      <div>Today</div>
      <div>Upcoming</div>
      <div class='category'>
        <div class="category-header">
          Categories
          <%= button_to '+', new_category_path, method: :get ,data: { turbo_frame: 'modal' } %>
        </div>
        <ul>
          <% @categories.each do |category| %>
            <li><%= category.title %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </section>
  <section class="app-body">
    List of task
  </section>
</div>

app/views/categories/_form.html.erb
<%= form_with model: @category, url: category_path do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, placeholder: 'Category', autofocus: true %>
  <div class="btns">
    <%= button_tag "Cancel", data: { action: 'modal#closeModal' }%>
    <%= form.submit 'Save' %>
  </div>
<% end %>
<div class="error">
  <% category.errors.full_messages.each do |message| %>
    <%= message.downcase %>
  <% end %>
</div>

app/views/categories/create.turbo_stream.erb
<%= turbo_stream.append "categories", @category %>

app/views/categories/new.html.erb
<%= turbo_frame_tag 'modal' do %>
  <div data-controller='modal'>
    <div class="modal-overlay">
      <div class="modal-form">
          <h1>Add Category</h1>
          <%= render 'form', category: @category %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeTrekker</title>
    <link rel="icon" href="<%= asset_path( 'stopwatch.png' ) %>" >
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= turbo_frame_tag 'modal', target: '_top' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<nav class="home-nav">
  <div class="nav-left">
    <div class="logo">
      <a href="/home"><%= image_tag "stopwatch.png", alt: "time trekker logo"%>
      <p class="logo-text">Time Trekker</p></a>
    </div>
    <%= link_to 'Features' %>
  </div>
  <div class="nav-right">
    <% if user_signed_in? %>
      <%= button_to 'Go to app', app_path, method: :get %>
    <% else %>
      <%= button_to 'Log in', new_user_session_path, data: { turbo: false }%>
      <%= button_to 'Sign up', new_user_registration_path, method: :get%>
    <% end %>
  </div>
</nav>